image: mono:latest

stages:
  - build

build:
  stage: build
  artifacts:
    paths:
      - Output/Release/MelonLoader/
      - BaseLibs/
  script:
  - echo building...
  - 'msbuild /p:Configuration=Release'
  except:
  - tags