<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(DotNetTarget)</TargetFramework>
        <RootNamespace>UnityEngine</RootNamespace>
        <OutputPath>$(MLOutDir)/MelonLoader</OutputPath>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Il2Cppmscorlib">
            <HintPath>..\..\Dependencies\SupportModules\Il2Cpp\Libs\Il2Cppmscorlib.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Il2CppSystem">
            <HintPath>..\..\Dependencies\SupportModules\Il2Cpp\Libs\Il2CppSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\..\Dependencies\SupportModules\Il2Cpp\Libs\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)\MelonLoader\MelonLoader.csproj" Private="false" />
        <PackageReference Include="AssetRipper.Primitives" Version="3.2.0" />
        <PackageReference Include="ds5678.Il2CppInterop.Runtime" Version="$(Il2CppInteropVersion)" Private="false">
          <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
