.code
extern winmm_procs:QWORD
CloseDriver_wrapper proc
	jmp winmm_procs[0*8]
CloseDriver_wrapper endp
DefDriverProc_wrapper proc
	jmp winmm_procs[1*8]
DefDriverProc_wrapper endp
DriverCallback_wrapper proc
	jmp winmm_procs[2*8]
DriverCallback_wrapper endp
DrvGetModuleHandle_wrapper proc
	jmp winmm_procs[3*8]
DrvGetModuleHandle_wrapper endp
GetDriverModuleHandle_wrapper proc
	jmp winmm_procs[4*8]
GetDriverModuleHandle_wrapper endp
OpenDriver_wrapper proc
	jmp winmm_procs[5*8]
OpenDriver_wrapper endp
PlaySound_wrapper proc
	jmp winmm_procs[6*8]
PlaySound_wrapper endp
PlaySoundA_wrapper proc
	jmp winmm_procs[7*8]
PlaySoundA_wrapper endp
PlaySoundW_wrapper proc
	jmp winmm_procs[8*8]
PlaySoundW_wrapper endp
SendDriverMessage_wrapper proc
	jmp winmm_procs[9*8]
SendDriverMessage_wrapper endp
WOWAppExit_wrapper proc
	jmp winmm_procs[10*8]
WOWAppExit_wrapper endp
auxGetDevCapsA_wrapper proc
	jmp winmm_procs[11*8]
auxGetDevCapsA_wrapper endp
auxGetDevCapsW_wrapper proc
	jmp winmm_procs[12*8]
auxGetDevCapsW_wrapper endp
auxGetNumDevs_wrapper proc
	jmp winmm_procs[13*8]
auxGetNumDevs_wrapper endp
auxGetVolume_wrapper proc
	jmp winmm_procs[14*8]
auxGetVolume_wrapper endp
auxOutMessage_wrapper proc
	jmp winmm_procs[15*8]
auxOutMessage_wrapper endp
auxSetVolume_wrapper proc
	jmp winmm_procs[16*8]
auxSetVolume_wrapper endp
joyConfigChanged_wrapper proc
	jmp winmm_procs[17*8]
joyConfigChanged_wrapper endp
joyGetDevCapsA_wrapper proc
	jmp winmm_procs[18*8]
joyGetDevCapsA_wrapper endp
joyGetDevCapsW_wrapper proc
	jmp winmm_procs[19*8]
joyGetDevCapsW_wrapper endp
joyGetNumDevs_wrapper proc
	jmp winmm_procs[20*8]
joyGetNumDevs_wrapper endp
joyGetPos_wrapper proc
	jmp winmm_procs[21*8]
joyGetPos_wrapper endp
joyGetPosEx_wrapper proc
	jmp winmm_procs[22*8]
joyGetPosEx_wrapper endp
joyGetThreshold_wrapper proc
	jmp winmm_procs[23*8]
joyGetThreshold_wrapper endp
joyReleaseCapture_wrapper proc
	jmp winmm_procs[24*8]
joyReleaseCapture_wrapper endp
joySetCapture_wrapper proc
	jmp winmm_procs[25*8]
joySetCapture_wrapper endp
joySetThreshold_wrapper proc
	jmp winmm_procs[26*8]
joySetThreshold_wrapper endp
mciDriverNotify_wrapper proc
	jmp winmm_procs[27*8]
mciDriverNotify_wrapper endp
mciDriverYield_wrapper proc
	jmp winmm_procs[28*8]
mciDriverYield_wrapper endp
mciExecute_wrapper proc
	jmp winmm_procs[29*8]
mciExecute_wrapper endp
mciFreeCommandResource_wrapper proc
	jmp winmm_procs[30*8]
mciFreeCommandResource_wrapper endp
mciGetCreatorTask_wrapper proc
	jmp winmm_procs[31*8]
mciGetCreatorTask_wrapper endp
mciGetDeviceIDA_wrapper proc
	jmp winmm_procs[32*8]
mciGetDeviceIDA_wrapper endp
mciGetDeviceIDFromElementIDA_wrapper proc
	jmp winmm_procs[33*8]
mciGetDeviceIDFromElementIDA_wrapper endp
mciGetDeviceIDFromElementIDW_wrapper proc
	jmp winmm_procs[34*8]
mciGetDeviceIDFromElementIDW_wrapper endp
mciGetDeviceIDW_wrapper proc
	jmp winmm_procs[35*8]
mciGetDeviceIDW_wrapper endp
mciGetDriverData_wrapper proc
	jmp winmm_procs[36*8]
mciGetDriverData_wrapper endp
mciGetErrorStringA_wrapper proc
	jmp winmm_procs[37*8]
mciGetErrorStringA_wrapper endp
mciGetErrorStringW_wrapper proc
	jmp winmm_procs[38*8]
mciGetErrorStringW_wrapper endp
mciGetYieldProc_wrapper proc
	jmp winmm_procs[39*8]
mciGetYieldProc_wrapper endp
mciLoadCommandResource_wrapper proc
	jmp winmm_procs[40*8]
mciLoadCommandResource_wrapper endp
mciSendCommandA_wrapper proc
	jmp winmm_procs[41*8]
mciSendCommandA_wrapper endp
mciSendCommandW_wrapper proc
	jmp winmm_procs[42*8]
mciSendCommandW_wrapper endp
mciSendStringA_wrapper proc
	jmp winmm_procs[43*8]
mciSendStringA_wrapper endp
mciSendStringW_wrapper proc
	jmp winmm_procs[44*8]
mciSendStringW_wrapper endp
mciSetDriverData_wrapper proc
	jmp winmm_procs[45*8]
mciSetDriverData_wrapper endp
mciSetYieldProc_wrapper proc
	jmp winmm_procs[46*8]
mciSetYieldProc_wrapper endp
midiConnect_wrapper proc
	jmp winmm_procs[47*8]
midiConnect_wrapper endp
midiDisconnect_wrapper proc
	jmp winmm_procs[48*8]
midiDisconnect_wrapper endp
midiInAddBuffer_wrapper proc
	jmp winmm_procs[49*8]
midiInAddBuffer_wrapper endp
midiInClose_wrapper proc
	jmp winmm_procs[50*8]
midiInClose_wrapper endp
midiInGetDevCapsA_wrapper proc
	jmp winmm_procs[51*8]
midiInGetDevCapsA_wrapper endp
midiInGetDevCapsW_wrapper proc
	jmp winmm_procs[52*8]
midiInGetDevCapsW_wrapper endp
midiInGetErrorTextA_wrapper proc
	jmp winmm_procs[53*8]
midiInGetErrorTextA_wrapper endp
midiInGetErrorTextW_wrapper proc
	jmp winmm_procs[54*8]
midiInGetErrorTextW_wrapper endp
midiInGetID_wrapper proc
	jmp winmm_procs[55*8]
midiInGetID_wrapper endp
midiInGetNumDevs_wrapper proc
	jmp winmm_procs[56*8]
midiInGetNumDevs_wrapper endp
midiInMessage_wrapper proc
	jmp winmm_procs[57*8]
midiInMessage_wrapper endp
midiInOpen_wrapper proc
	jmp winmm_procs[58*8]
midiInOpen_wrapper endp
midiInPrepareHeader_wrapper proc
	jmp winmm_procs[59*8]
midiInPrepareHeader_wrapper endp
midiInReset_wrapper proc
	jmp winmm_procs[60*8]
midiInReset_wrapper endp
midiInStart_wrapper proc
	jmp winmm_procs[61*8]
midiInStart_wrapper endp
midiInStop_wrapper proc
	jmp winmm_procs[62*8]
midiInStop_wrapper endp
midiInUnprepareHeader_wrapper proc
	jmp winmm_procs[63*8]
midiInUnprepareHeader_wrapper endp
midiOutCacheDrumPatches_wrapper proc
	jmp winmm_procs[64*8]
midiOutCacheDrumPatches_wrapper endp
midiOutCachePatches_wrapper proc
	jmp winmm_procs[65*8]
midiOutCachePatches_wrapper endp
midiOutClose_wrapper proc
	jmp winmm_procs[66*8]
midiOutClose_wrapper endp
midiOutGetDevCapsA_wrapper proc
	jmp winmm_procs[67*8]
midiOutGetDevCapsA_wrapper endp
midiOutGetDevCapsW_wrapper proc
	jmp winmm_procs[68*8]
midiOutGetDevCapsW_wrapper endp
midiOutGetErrorTextA_wrapper proc
	jmp winmm_procs[69*8]
midiOutGetErrorTextA_wrapper endp
midiOutGetErrorTextW_wrapper proc
	jmp winmm_procs[70*8]
midiOutGetErrorTextW_wrapper endp
midiOutGetID_wrapper proc
	jmp winmm_procs[71*8]
midiOutGetID_wrapper endp
midiOutGetNumDevs_wrapper proc
	jmp winmm_procs[72*8]
midiOutGetNumDevs_wrapper endp
midiOutGetVolume_wrapper proc
	jmp winmm_procs[73*8]
midiOutGetVolume_wrapper endp
midiOutLongMsg_wrapper proc
	jmp winmm_procs[74*8]
midiOutLongMsg_wrapper endp
midiOutMessage_wrapper proc
	jmp winmm_procs[75*8]
midiOutMessage_wrapper endp
midiOutOpen_wrapper proc
	jmp winmm_procs[76*8]
midiOutOpen_wrapper endp
midiOutPrepareHeader_wrapper proc
	jmp winmm_procs[77*8]
midiOutPrepareHeader_wrapper endp
midiOutReset_wrapper proc
	jmp winmm_procs[78*8]
midiOutReset_wrapper endp
midiOutSetVolume_wrapper proc
	jmp winmm_procs[79*8]
midiOutSetVolume_wrapper endp
midiOutShortMsg_wrapper proc
	jmp winmm_procs[80*8]
midiOutShortMsg_wrapper endp
midiOutUnprepareHeader_wrapper proc
	jmp winmm_procs[81*8]
midiOutUnprepareHeader_wrapper endp
midiStreamClose_wrapper proc
	jmp winmm_procs[82*8]
midiStreamClose_wrapper endp
midiStreamOpen_wrapper proc
	jmp winmm_procs[83*8]
midiStreamOpen_wrapper endp
midiStreamOut_wrapper proc
	jmp winmm_procs[84*8]
midiStreamOut_wrapper endp
midiStreamPause_wrapper proc
	jmp winmm_procs[85*8]
midiStreamPause_wrapper endp
midiStreamPosition_wrapper proc
	jmp winmm_procs[86*8]
midiStreamPosition_wrapper endp
midiStreamProperty_wrapper proc
	jmp winmm_procs[87*8]
midiStreamProperty_wrapper endp
midiStreamRestart_wrapper proc
	jmp winmm_procs[88*8]
midiStreamRestart_wrapper endp
midiStreamStop_wrapper proc
	jmp winmm_procs[89*8]
midiStreamStop_wrapper endp
mixerClose_wrapper proc
	jmp winmm_procs[90*8]
mixerClose_wrapper endp
mixerGetControlDetailsA_wrapper proc
	jmp winmm_procs[91*8]
mixerGetControlDetailsA_wrapper endp
mixerGetControlDetailsW_wrapper proc
	jmp winmm_procs[92*8]
mixerGetControlDetailsW_wrapper endp
mixerGetDevCapsA_wrapper proc
	jmp winmm_procs[93*8]
mixerGetDevCapsA_wrapper endp
mixerGetDevCapsW_wrapper proc
	jmp winmm_procs[94*8]
mixerGetDevCapsW_wrapper endp
mixerGetID_wrapper proc
	jmp winmm_procs[95*8]
mixerGetID_wrapper endp
mixerGetLineControlsA_wrapper proc
	jmp winmm_procs[96*8]
mixerGetLineControlsA_wrapper endp
mixerGetLineControlsW_wrapper proc
	jmp winmm_procs[97*8]
mixerGetLineControlsW_wrapper endp
mixerGetLineInfoA_wrapper proc
	jmp winmm_procs[98*8]
mixerGetLineInfoA_wrapper endp
mixerGetLineInfoW_wrapper proc
	jmp winmm_procs[99*8]
mixerGetLineInfoW_wrapper endp
mixerGetNumDevs_wrapper proc
	jmp winmm_procs[100*8]
mixerGetNumDevs_wrapper endp
mixerMessage_wrapper proc
	jmp winmm_procs[101*8]
mixerMessage_wrapper endp
mixerOpen_wrapper proc
	jmp winmm_procs[102*8]
mixerOpen_wrapper endp
mixerSetControlDetails_wrapper proc
	jmp winmm_procs[103*8]
mixerSetControlDetails_wrapper endp
mmDrvInstall_wrapper proc
	jmp winmm_procs[104*8]
mmDrvInstall_wrapper endp
mmGetCurrentTask_wrapper proc
	jmp winmm_procs[105*8]
mmGetCurrentTask_wrapper endp
mmTaskBlock_wrapper proc
	jmp winmm_procs[106*8]
mmTaskBlock_wrapper endp
mmTaskCreate_wrapper proc
	jmp winmm_procs[107*8]
mmTaskCreate_wrapper endp
mmTaskSignal_wrapper proc
	jmp winmm_procs[108*8]
mmTaskSignal_wrapper endp
mmTaskYield_wrapper proc
	jmp winmm_procs[109*8]
mmTaskYield_wrapper endp
mmioAdvance_wrapper proc
	jmp winmm_procs[110*8]
mmioAdvance_wrapper endp
mmioAscend_wrapper proc
	jmp winmm_procs[111*8]
mmioAscend_wrapper endp
mmioClose_wrapper proc
	jmp winmm_procs[112*8]
mmioClose_wrapper endp
mmioCreateChunk_wrapper proc
	jmp winmm_procs[113*8]
mmioCreateChunk_wrapper endp
mmioDescend_wrapper proc
	jmp winmm_procs[114*8]
mmioDescend_wrapper endp
mmioFlush_wrapper proc
	jmp winmm_procs[115*8]
mmioFlush_wrapper endp
mmioGetInfo_wrapper proc
	jmp winmm_procs[116*8]
mmioGetInfo_wrapper endp
mmioInstallIOProcA_wrapper proc
	jmp winmm_procs[117*8]
mmioInstallIOProcA_wrapper endp
mmioInstallIOProcW_wrapper proc
	jmp winmm_procs[118*8]
mmioInstallIOProcW_wrapper endp
mmioOpenA_wrapper proc
	jmp winmm_procs[119*8]
mmioOpenA_wrapper endp
mmioOpenW_wrapper proc
	jmp winmm_procs[120*8]
mmioOpenW_wrapper endp
mmioRead_wrapper proc
	jmp winmm_procs[121*8]
mmioRead_wrapper endp
mmioRenameA_wrapper proc
	jmp winmm_procs[122*8]
mmioRenameA_wrapper endp
mmioRenameW_wrapper proc
	jmp winmm_procs[123*8]
mmioRenameW_wrapper endp
mmioSeek_wrapper proc
	jmp winmm_procs[124*8]
mmioSeek_wrapper endp
mmioSendMessage_wrapper proc
	jmp winmm_procs[125*8]
mmioSendMessage_wrapper endp
mmioSetBuffer_wrapper proc
	jmp winmm_procs[126*8]
mmioSetBuffer_wrapper endp
mmioSetInfo_wrapper proc
	jmp winmm_procs[127*8]
mmioSetInfo_wrapper endp
mmioStringToFOURCCA_wrapper proc
	jmp winmm_procs[128*8]
mmioStringToFOURCCA_wrapper endp
mmioStringToFOURCCW_wrapper proc
	jmp winmm_procs[129*8]
mmioStringToFOURCCW_wrapper endp
mmioWrite_wrapper proc
	jmp winmm_procs[130*8]
mmioWrite_wrapper endp
mmsystemGetVersion_wrapper proc
	jmp winmm_procs[131*8]
mmsystemGetVersion_wrapper endp
sndPlaySoundA_wrapper proc
	jmp winmm_procs[132*8]
sndPlaySoundA_wrapper endp
sndPlaySoundW_wrapper proc
	jmp winmm_procs[133*8]
sndPlaySoundW_wrapper endp
timeBeginPeriod_wrapper proc
	jmp winmm_procs[134*8]
timeBeginPeriod_wrapper endp
timeEndPeriod_wrapper proc
	jmp winmm_procs[135*8]
timeEndPeriod_wrapper endp
timeGetDevCaps_wrapper proc
	jmp winmm_procs[136*8]
timeGetDevCaps_wrapper endp
timeGetSystemTime_wrapper proc
	jmp winmm_procs[137*8]
timeGetSystemTime_wrapper endp
timeGetTime_wrapper proc
	jmp winmm_procs[138*8]
timeGetTime_wrapper endp
timeKillEvent_wrapper proc
	jmp winmm_procs[139*8]
timeKillEvent_wrapper endp
timeSetEvent_wrapper proc
	jmp winmm_procs[140*8]
timeSetEvent_wrapper endp
waveInAddBuffer_wrapper proc
	jmp winmm_procs[141*8]
waveInAddBuffer_wrapper endp
waveInClose_wrapper proc
	jmp winmm_procs[142*8]
waveInClose_wrapper endp
waveInGetDevCapsA_wrapper proc
	jmp winmm_procs[143*8]
waveInGetDevCapsA_wrapper endp
waveInGetDevCapsW_wrapper proc
	jmp winmm_procs[144*8]
waveInGetDevCapsW_wrapper endp
waveInGetErrorTextA_wrapper proc
	jmp winmm_procs[145*8]
waveInGetErrorTextA_wrapper endp
waveInGetErrorTextW_wrapper proc
	jmp winmm_procs[146*8]
waveInGetErrorTextW_wrapper endp
waveInGetID_wrapper proc
	jmp winmm_procs[147*8]
waveInGetID_wrapper endp
waveInGetNumDevs_wrapper proc
	jmp winmm_procs[148*8]
waveInGetNumDevs_wrapper endp
waveInGetPosition_wrapper proc
	jmp winmm_procs[149*8]
waveInGetPosition_wrapper endp
waveInMessage_wrapper proc
	jmp winmm_procs[150*8]
waveInMessage_wrapper endp
waveInOpen_wrapper proc
	jmp winmm_procs[151*8]
waveInOpen_wrapper endp
waveInPrepareHeader_wrapper proc
	jmp winmm_procs[152*8]
waveInPrepareHeader_wrapper endp
waveInReset_wrapper proc
	jmp winmm_procs[153*8]
waveInReset_wrapper endp
waveInStart_wrapper proc
	jmp winmm_procs[154*8]
waveInStart_wrapper endp
waveInStop_wrapper proc
	jmp winmm_procs[155*8]
waveInStop_wrapper endp
waveInUnprepareHeader_wrapper proc
	jmp winmm_procs[156*8]
waveInUnprepareHeader_wrapper endp
waveOutBreakLoop_wrapper proc
	jmp winmm_procs[157*8]
waveOutBreakLoop_wrapper endp
waveOutClose_wrapper proc
	jmp winmm_procs[158*8]
waveOutClose_wrapper endp
waveOutGetDevCapsA_wrapper proc
	jmp winmm_procs[159*8]
waveOutGetDevCapsA_wrapper endp
waveOutGetDevCapsW_wrapper proc
	jmp winmm_procs[160*8]
waveOutGetDevCapsW_wrapper endp
waveOutGetErrorTextA_wrapper proc
	jmp winmm_procs[161*8]
waveOutGetErrorTextA_wrapper endp
waveOutGetErrorTextW_wrapper proc
	jmp winmm_procs[162*8]
waveOutGetErrorTextW_wrapper endp
waveOutGetID_wrapper proc
	jmp winmm_procs[163*8]
waveOutGetID_wrapper endp
waveOutGetNumDevs_wrapper proc
	jmp winmm_procs[164*8]
waveOutGetNumDevs_wrapper endp
waveOutGetPitch_wrapper proc
	jmp winmm_procs[165*8]
waveOutGetPitch_wrapper endp
waveOutGetPlaybackRate_wrapper proc
	jmp winmm_procs[166*8]
waveOutGetPlaybackRate_wrapper endp
waveOutGetPosition_wrapper proc
	jmp winmm_procs[167*8]
waveOutGetPosition_wrapper endp
waveOutGetVolume_wrapper proc
	jmp winmm_procs[168*8]
waveOutGetVolume_wrapper endp
waveOutMessage_wrapper proc
	jmp winmm_procs[169*8]
waveOutMessage_wrapper endp
waveOutOpen_wrapper proc
	jmp winmm_procs[170*8]
waveOutOpen_wrapper endp
waveOutPause_wrapper proc
	jmp winmm_procs[171*8]
waveOutPause_wrapper endp
waveOutPrepareHeader_wrapper proc
	jmp winmm_procs[172*8]
waveOutPrepareHeader_wrapper endp
waveOutReset_wrapper proc
	jmp winmm_procs[173*8]
waveOutReset_wrapper endp
waveOutRestart_wrapper proc
	jmp winmm_procs[174*8]
waveOutRestart_wrapper endp
waveOutSetPitch_wrapper proc
	jmp winmm_procs[175*8]
waveOutSetPitch_wrapper endp
waveOutSetPlaybackRate_wrapper proc
	jmp winmm_procs[176*8]
waveOutSetPlaybackRate_wrapper endp
waveOutSetVolume_wrapper proc
	jmp winmm_procs[177*8]
waveOutSetVolume_wrapper endp
waveOutUnprepareHeader_wrapper proc
	jmp winmm_procs[178*8]
waveOutUnprepareHeader_wrapper endp
waveOutWrite_wrapper proc
	jmp winmm_procs[179*8]
waveOutWrite_wrapper endp
ExportByOrdinal2 proc
	jmp winmm_procs[180*8]
ExportByOrdinal2 endp
end
