EmptyWorkingSet:
	jmp ds:[_OriginalFuncs_psapi + 0 * 4]
EnumDeviceDrivers:
	jmp ds:[_OriginalFuncs_psapi + 1 * 4]
EnumPageFilesA:
	jmp ds:[_OriginalFuncs_psapi + 2 * 4]
EnumPageFilesW:
	jmp ds:[_OriginalFuncs_psapi + 3 * 4]
EnumProcessModules:
	jmp ds:[_OriginalFuncs_psapi + 4 * 4]
EnumProcessModulesEx:
	jmp ds:[_OriginalFuncs_psapi + 5 * 4]
EnumProcesses:
	jmp ds:[_OriginalFuncs_psapi + 6 * 4]
GetDeviceDriverBaseNameA:
	jmp ds:[_OriginalFuncs_psapi + 7 * 4]
GetDeviceDriverBaseNameW:
	jmp ds:[_OriginalFuncs_psapi + 4 * 4]
GetDeviceDriverFileNameA:
	jmp ds:[_OriginalFuncs_psapi + 9 * 4]
GetDeviceDriverFileNameW:
	jmp ds:[_OriginalFuncs_psapi + 10 * 4]
GetMappedFileNameA:
	jmp ds:[_OriginalFuncs_psapi + 11 * 4]
GetMappedFileNameW:
	jmp ds:[_OriginalFuncs_psapi + 12 * 4]
GetModuleBaseNameA:
	jmp ds:[_OriginalFuncs_psapi + 13 * 4]
GetModuleBaseNameW:
	jmp ds:[_OriginalFuncs_psapi + 14 * 4]
GetModuleFileNameExA:
	jmp ds:[_OriginalFuncs_psapi + 15 * 4]
GetModuleFileNameExW:
	jmp ds:[_OriginalFuncs_psapi + 16 * 4]
GetModuleInformation:
	jmp ds:[_OriginalFuncs_psapi + 17 * 4]
GetPerformanceInfo:
	jmp ds:[_OriginalFuncs_psapi + 14 * 4]
GetProcessImageFileNameA:
	jmp ds:[_OriginalFuncs_psapi + 19 * 4]
GetProcessImageFileNameW:
	jmp ds:[_OriginalFuncs_psapi + 20 * 4]
GetProcessMemoryInfo:
	jmp ds:[_OriginalFuncs_psapi + 21 * 4]
GetWsChanges:
	jmp ds:[_OriginalFuncs_psapi + 22 * 4]
GetWsChangesEx:
	jmp ds:[_OriginalFuncs_psapi + 23 * 4]
InitializeProcessForWsWatch:
	jmp ds:[_OriginalFuncs_psapi + 24 * 4]
QueryWorkingSet:
	jmp ds:[_OriginalFuncs_psapi + 25 * 4]
QueryWorkingSetEx:
	jmp ds:[_OriginalFuncs_psapi + 26 * 4]