EmptyWorkingSet:
	jmp qword ptr [rip + OriginalFuncs_psapi + 0 * 8]
EnumDeviceDrivers:
	jmp qword ptr [rip + OriginalFuncs_psapi + 1 * 8]
EnumPageFilesA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 2 * 8]
EnumPageFilesW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 3 * 8]
EnumProcessModules:
	jmp qword ptr [rip + OriginalFuncs_psapi + 4 * 8]
EnumProcessModulesEx:
	jmp qword ptr [rip + OriginalFuncs_psapi + 5 * 8]
EnumProcesses:
	jmp qword ptr [rip + OriginalFuncs_psapi + 6 * 8]
GetDeviceDriverBaseNameA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 7 * 8]
GetDeviceDriverBaseNameW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 8 * 8]
GetDeviceDriverFileNameA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 9 * 8]
GetDeviceDriverFileNameW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 10 * 8]
GetMappedFileNameA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 11 * 8]
GetMappedFileNameW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 12 * 8]
GetModuleBaseNameA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 13 * 8]
GetModuleBaseNameW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 14 * 8]
GetModuleFileNameExA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 15 * 8]
GetModuleFileNameExW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 16 * 8]
GetModuleInformation:
	jmp qword ptr [rip + OriginalFuncs_psapi + 17 * 8]
GetPerformanceInfo:
	jmp qword ptr [rip + OriginalFuncs_psapi + 18 * 8]
GetProcessImageFileNameA:
	jmp qword ptr [rip + OriginalFuncs_psapi + 19 * 8]
GetProcessImageFileNameW:
	jmp qword ptr [rip + OriginalFuncs_psapi + 20 * 8]
GetProcessMemoryInfo:
	jmp qword ptr [rip + OriginalFuncs_psapi + 21 * 8]
GetWsChanges:
	jmp qword ptr [rip + OriginalFuncs_psapi + 22 * 8]
GetWsChangesEx:
	jmp qword ptr [rip + OriginalFuncs_psapi + 23 * 8]
InitializeProcessForWsWatch:
	jmp qword ptr [rip + OriginalFuncs_psapi + 24 * 8]
QueryWorkingSet:
	jmp qword ptr [rip + OriginalFuncs_psapi + 25 * 8]
QueryWorkingSetEx:
	jmp qword ptr [rip + OriginalFuncs_psapi + 26 * 8]