.globl Private1
.globl SvchostPushServiceGlobals
.globl WinHttpAddRequestHeaders
.globl WinHttpAutoProxySvcMain
.globl WinHttpCheckPlatform
.globl WinHttpCloseHandle
.globl WinHttpConnect
.globl WinHttpConnectionDeletePolicyEntries
.globl WinHttpConnectionDeleteProxyInfo
.globl WinHttpConnectionFreeNameList
.globl WinHttpConnectionFreeProxyInfo
.globl WinHttpConnectionFreeProxyList
.globl WinHttpConnectionGetNameList
.globl WinHttpConnectionGetProxyInfo
.globl WinHttpConnectionGetProxyList
.globl WinHttpConnectionSetPolicyEntries
.globl WinHttpConnectionSetProxyInfo
.globl WinHttpConnectionUpdateIfIndexTable
.globl WinHttpCrackUrl
.globl WinHttpCreateProxyResolver
.globl WinHttpCreateUrl
.globl WinHttpDetectAutoProxyConfigUrl
.globl WinHttpFreeProxyResult
.globl WinHttpFreeProxyResultEx
.globl WinHttpFreeProxySettings
.globl WinHttpGetDefaultProxyConfiguration
.globl WinHttpGetIEProxyConfigForCurrentUser
.globl WinHttpGetProxyForUrl
.globl WinHttpGetProxyForUrlEx
.globl WinHttpGetProxyForUrlEx2
.globl WinHttpGetProxyForUrlHvsi
.globl WinHttpGetProxyResult
.globl WinHttpGetProxyResultEx
.globl WinHttpGetProxySettingsVersion
.globl WinHttpGetTunnelSocket
.globl WinHttpOpen
.globl WinHttpOpenRequest
.globl WinHttpPacJsWorkerMain
.globl WinHttpProbeConnectivity
.globl WinHttpQueryAuthSchemes
.globl WinHttpQueryDataAvailable
.globl WinHttpQueryHeaders
.globl WinHttpQueryOption
.globl WinHttpReadData
.globl WinHttpReadProxySettings
.globl WinHttpReadProxySettingsHvsi
.globl WinHttpReceiveResponse
.globl WinHttpResetAutoProxy
.globl WinHttpSaveProxyCredentials
.globl WinHttpSendRequest
.globl WinHttpSetCredentials
.globl WinHttpSetDefaultProxyConfiguration
.globl WinHttpSetOption
.globl WinHttpSetStatusCallback
.globl WinHttpSetTimeouts
.globl WinHttpTimeFromSystemTime
.globl WinHttpTimeToSystemTime
.globl WinHttpWebSocketClose
.globl WinHttpWebSocketCompleteUpgrade
.globl WinHttpWebSocketQueryCloseStatus
.globl WinHttpWebSocketReceive
.globl WinHttpWebSocketSend
.globl WinHttpWebSocketShutdown
.globl WinHttpWriteData
.globl WinHttpWriteProxySettings

Private1:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 0 * 8]
SvchostPushServiceGlobals:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 1 * 8]
WinHttpAddRequestHeaders:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 2 * 8]
WinHttpAutoProxySvcMain:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 3 * 8]
WinHttpCheckPlatform:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 4 * 8]
WinHttpCloseHandle:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 5 * 8]
WinHttpConnect:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 6 * 8]
WinHttpConnectionDeletePolicyEntries:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 7 * 8]
WinHttpConnectionDeleteProxyInfo:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 8 * 8]
WinHttpConnectionFreeNameList:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 9 * 8]
WinHttpConnectionFreeProxyInfo:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 10 * 8]
WinHttpConnectionFreeProxyList:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 11 * 8]
WinHttpConnectionGetNameList:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 12 * 8]
WinHttpConnectionGetProxyInfo:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 13 * 8]
WinHttpConnectionGetProxyList:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 14 * 8]
WinHttpConnectionSetPolicyEntries:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 15 * 8]
WinHttpConnectionSetProxyInfo:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 16 * 8]
WinHttpConnectionUpdateIfIndexTable:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 17 * 8]
WinHttpCrackUrl:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 18 * 8]
WinHttpCreateProxyResolver:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 19 * 8]
WinHttpCreateUrl:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 20 * 8]
WinHttpDetectAutoProxyConfigUrl:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 21 * 8]
WinHttpFreeProxyResult:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 22 * 8]
WinHttpFreeProxyResultEx:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 23 * 8]
WinHttpFreeProxySettings:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 24 * 8]
WinHttpGetDefaultProxyConfiguration:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 25 * 8]
WinHttpGetIEProxyConfigForCurrentUser:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 26 * 8]
WinHttpGetProxyForUrl:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 27 * 8]
WinHttpGetProxyForUrlEx:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 28 * 8]
WinHttpGetProxyForUrlEx2:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 29 * 8]
WinHttpGetProxyForUrlHvsi:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 30 * 8]
WinHttpGetProxyResult:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 31 * 8]
WinHttpGetProxyResultEx:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 32 * 8]
WinHttpGetProxySettingsVersion:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 33 * 8]
WinHttpGetTunnelSocket:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 34 * 8]
WinHttpOpen:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 35 * 8]
WinHttpOpenRequest:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 36 * 8]
WinHttpPacJsWorkerMain:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 37 * 8]
WinHttpProbeConnectivity:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 38 * 8]
WinHttpQueryAuthSchemes:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 39 * 8]
WinHttpQueryDataAvailable:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 40 * 8]
WinHttpQueryHeaders:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 41 * 8]
WinHttpQueryOption:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 42 * 8]
WinHttpReadData:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 43 * 8]
WinHttpReadProxySettings:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 44 * 8]
WinHttpReadProxySettingsHvsi:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 45 * 8]
WinHttpReceiveResponse:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 46 * 8]
WinHttpResetAutoProxy:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 47 * 8]
WinHttpSaveProxyCredentials:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 48 * 8]
WinHttpSendRequest:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 49 * 8]
WinHttpSetCredentials:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 50 * 8]
WinHttpSetDefaultProxyConfiguration:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 51 * 8]
WinHttpSetOption:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 52 * 8]
WinHttpSetStatusCallback:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 53 * 8]
WinHttpSetTimeouts:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 54 * 8]
WinHttpTimeFromSystemTime:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 55 * 8]
WinHttpTimeToSystemTime:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 56 * 8]
WinHttpWebSocketClose:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 57 * 8]
WinHttpWebSocketCompleteUpgrade:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 58 * 8]
WinHttpWebSocketQueryCloseStatus:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 59 * 8]
WinHttpWebSocketReceive:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 60 * 8]
WinHttpWebSocketSend:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 61 * 8]
WinHttpWebSocketShutdown:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 62 * 8]
WinHttpWriteData:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 63 * 8]
WinHttpWriteProxySettings:
	jmp qword ptr [rip + OriginalFuncs_winhttp + 64 * 8]
