<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$([System.Environment]::GetFolderPath(SpecialFolder.UserProfile))/.nuget/packages/monomod.runtimedetour/22.7.31.1/lib/net5.0/MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Compile Include="../../MelonLoader/Fixes/MonoMod/MacOSArm64NativeDetourPlatform.cs" Link="MacOSArm64NativeDetourPlatform.cs" />
  </ItemGroup>
</Project>
