on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      SKIP_DEBUG:
        required: true
        type: boolean
      PACKAGE_VERSION:
        required: true
        type: string
      PACKAGE_NAME:
        required: true
        type: string

jobs:
  compile_windows:
    name: Windows
    uses: ./.github/workflows/compile_windows.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      SKIP_DEBUG: ${{ inputs.SKIP_DEBUG }}
      
  compile_linux:
    name: Linux
    uses: ./.github/workflows/compile_linux.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      SKIP_DEBUG: ${{ inputs.SKIP_DEBUG }}
      
  compile_macos:
    name: MacOS
    uses: ./.github/workflows/compile_macos.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      SKIP_DEBUG: ${{ inputs.SKIP_DEBUG }}
      
  compile_nuget:
    name: NuGet
    uses: ./.github/workflows/compile_nuget.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      
  compile_thunderstore:
    name: Thunderstore
    uses: ./.github/workflows/compile_thunderstore.yml
    needs: [ compile_windows ]
    with:
      VERSION: ${{ inputs.PACKAGE_VERSION }}
      PACKAGE_NAME: ${{ inputs.PACKAGE_NAME }}